config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  root 'welcome#index'

  resource :users , only: [:show]

  resources :accounts do
    get 'confirm', on: :collection
    get 'balance', on: :collection
  end

  resources :admin, only: [:index]

  resources :loan, only: [:index, :new, :create]
  
  resources :transactions

  # deposit
  get 'deposit', to: "accounts#deposit"
  get 'deposit/:id', to: "accounts#deposit_money"
  patch 'deposit/:id', to: "accounts#deposit_amount"

  # withdrawals
  get 'withdraw', to: "accounts#withdraw"
  get 'withdraw/:id', to: "accounts#withdraw_money"
  patch 'withdraw/:id', to: "accounts#withdraw_amount"

  # Atm withdrawal 
  get 'atmwithdraw/:id', to: "accounts#atmwithdraw"
  patch 'atmwithdraw/:id', to: "accounts#atmwithdraw_amount"

  # money transfer
  get 'transfer', to: "accounts#transfer"
  get 'transfer/:id', to: "accounts#transfer_money"
  patch 'transfer/:id', to: "accounts#transfer_amount"

  # search user in admin  
  get 'search_user', to: 'admin#search'

  # api collection
  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth', controllers:{
      sessions: 'api/sessions'
    }
    defaults format: :json do

      resources :user, only: [:index]
      post 'accounts', to: "accounts#create"
      get 'details', to: "user#details"
      get 'balance', to: "accounts#balance"
      get 'transactions', to: "transactions#transactions"
      post 'deposit', to: "transactions#deposit"
      post 'withdraw', to: "accounts#withdraw"
      post 'transfer', to: "accounts#transfer"
      post 'loan', to: "loan#loan"
      post 'atmwithdraw', to: "accounts#atmwithdraw"
    end
  end
   

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :check_signed_in?

    def index
        @users = User.where(admin: false)
    end

    def search
      if params[:user].present?
        @users = User.search(params[:user])
        if @users
          respond_to do |format|
            format.js { render partial: 'dashboard/user_result' }
          end
          
        else
          respond_to do |format|
            flash.now[:alert] = "Couldn't find user"
            format.js { render partial: 'dashboard/user_result' }
          end
        end    
      else
        respond_to do |format|
          flash.now[:alert] = "Please enter a user name or email to search"
          format.js { render partial: 'dashboard/user_result' }
        end
      end
    end

    def check_signed_in?
      unless user_signed_in?
        flash[:alert] = "Please sign in or sign up."
        redirect_to root_path
      end
    end
end

app/views/dashboard/_user_result.html.erb
<div class="container content-center">
    <div class="row justify-content-center">
        <div class="col">
            <%= "Customer Id" %> 
        </div>
        <div class="col">
            <%= "Name:" %> 
        </div>
        <div class="col">
            <%= "Details" %> 
        </div>
        <div class="col">
            <%= "Transactions" %> 
        </div>
    </div>
    <br>
    
    <% @users.each do |user|%>
        <div class="row justify-content-center">
            <div class="col">
                <%= user.id%> 
            </div>
            <div class="col">
                <%= "#{user.first_name.capitalize} #{user.last_name.capitalize}"%> 
            </div>
            <div class="col">
                <%= link_to ("User Details"), details_path( id: "#{user.id}"),class:"btn btn-outline-success"%>  
                
            </div>
            <div class="col">
                <%= link_to ("Transaction History"), transactions_path( id: "#{user.id}"),class:"btn btn-outline-success"%>  
            </div>
        </div>
    <%end %>
</div>

app/views/dashboard/index.html.erb
<br>
<div class='search-area'>
   <h3>Search User</h3>
   <%= form_tag search_user_path, remote: true, method: :get do %>
     <div class="form-group row">
       <div class="col-sm-9 no-right-padding">
         <%= text_field_tag :user, params[:user], placeholder: "Name or email", autofocus: true, class: "form-control form-control-lg" %>
       </div>
       <div class="col-sm-3 no-left-padding">
         <%= button_tag type: :submit, class: "btn btn-success" do %>
           search
         <% end %>
       </div>
     </div>
   <% end %>
 </div>

 <div id="user-results">

 </div>
 <br>
<div class="container content-center">
    <div class="row justify-content-center">
        <div class="col">
            <%= "Customer Id" %> 
        </div>
        <div class="col">
            <%= "Name:" %> 
        </div>
        <div class="col">
            <%= "Details" %> 
        </div>
        <div class="col">
            <%= "Transactions" %> 
        </div>
    </div>
    <br>
    
    <% @users.each do |user|%>
        <div class="row justify-content-center">
            <div class="col">
                <%= user.id%> 
            </div>
            <div class="col">
                <%= "#{user.first_name.capitalize} #{user.last_name.capitalize}"%> 
            </div>
            <div class="col">
                <%= link_to ("User Details"), details_path( id: "#{user.id}"),class:"btn btn-outline-success"%>  
                
            </div>
            <div class="col">
                <%= link_to ("Transaction History"), transactions_path( id: "#{user.id}"),class:"btn btn-outline-success"%>  
            </div>
        </div>
        <br>
    <%end %>
</div>
<%= link_to ("Back"), root_path,  class:"btn btn-outline-success my-2 my-sm-0"%> 