config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  root 'welcome#index'

  resource :users , only: [:show]

  resources :accounts do
    get 'confirm', on: :collection
    get 'balance', on: :collection
  end

  resources :admin, only: [:index]

  resources :loan, only: [:index, :new, :create]
  
  resources :transactions

  # deposit
  get 'deposit', to: "accounts#deposit"
  get 'deposit/:id', to: "accounts#deposit_money"
  patch 'deposit/:id', to: "accounts#deposit_amount"

  # withdrawals
  get 'withdraw', to: "accounts#withdraw"
  get 'withdraw/:id', to: "accounts#withdraw_money"
  patch 'withdraw/:id', to: "accounts#withdraw_amount"

  # Atm withdrawal 
  get 'atmwithdraw/:id', to: "accounts#atmwithdraw"
  patch 'atmwithdraw/:id', to: "accounts#atmwithdraw_amount"

  # money transfer
  get 'transfer', to: "accounts#transfer"
  get 'transfer/:id', to: "accounts#transfer_money"
  patch 'transfer/:id', to: "accounts#transfer_amount"

  # search user in admin  
  get 'search_user', to: 'admin#search'

  # api collection
  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth', controllers:{
      sessions: 'api/sessions'
    }
    defaults format: :json do

      resources :user, only: [:index]
      post 'accounts', to: "accounts#create"
      get 'details', to: "user#details"
      get 'balance', to: "accounts#balance"
      get 'transactions', to: "transactions#transactions"
      post 'deposit', to: "transactions#deposit"
      post 'withdraw', to: "accounts#withdraw"
      post 'transfer', to: "accounts#transfer"
      post 'loan', to: "loan#loan"
      post 'atmwithdraw', to: "accounts#atmwithdraw"
    end
  end
   

end

app/models/account.rb
class Account < ApplicationRecord
    belongs_to :user
    belongs_to :branch
    has_many :transactions, dependent: :destroy
    has_one :atm, dependent: :destroy
    has_one :loan, dependent: :destroy
    
    validates_uniqueness_of :number
    validates :number,  numericality: true
    validates_length_of :number, :maximum => 10, :minimum => 10

    validates_with AccountValidator
    after_create :transaction_atm

    def transaction_atm
        account = Account.last
        Transaction.create(type_of_transaction: "Direct", medium: "Deposit",account_id: account.id,amount: account.balance, where: (account.number).to_s, remark: "Opening balance", balance: account.balance)
        Atm.create(account_id: account.id,expiry_date: DateTime.now.next_year(5).to_date,cvv: rand(100 .. 999),number: rand(1000000000000000 .. 9999999999999999))
    end

end

app/controllers/accounts_controller.rb
class   AccountsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_up_accounts_variable, only: [:transfer, :withdraw,:balance]
    before_action :set_up_account_variable, only: [:atmwithdraw,:transfer_money,:withdraw_money,:withdraw_amount,:atmwithdraw_amount]
    before_action :set_up_user_variable, only: [:new,:create]
    before_action :set_up_new_account_variable, only: [:new,:confirm]
    
    def index 

    end

    def new
        
    end

    def create 
        @account = Account.new(user_id: @user.id, type_of_account: params[:account][:type_of_account], branch_id: (params[:account][:branch_id]).to_i,balance: (params[:account][:balance]).to_f, number: rand(1000000000 .. 9999999999))
        if @account.save
            message_and_redirect(:notice,"Account has been created successfully")
        else
            message_and_redirect(:alert,"#{@account.errors.each{|error| p error}}")
        end
    end

    def confirm 
        respond_partial("open_account")
    end

    def balance
        
    end

    # deposit
    def deposit
        @accounts = current_user.accounts
    end

    def deposit_money
        @account = Account.find(params[:id])
        respond_partial("deposit-money")
    end

    def deposit_amount
        @account = Account.find(params[:id])
        if @account.type_of_account == "Loan"
            loan_deposit
        else
            direct_transaction
        end
    end

    # direct withdrawal
    def withdraw
        
    end

    def withdraw_money
        respond_partial("withdraw-money")
    end

    def withdraw_amount
        @account.transaction do
            withdrawal_transaction
        end
    end

    # transfer money
    def transfer
        
    end

    def transfer_money
        respond_partial("transfer-money")
    end

    def transfer_amount
        unless Account.find_by(number: (params[:number]).to_i)
            message_and_redirect(:alert,"Incorrect Account number")
        else
            @account = Account.find(params[:id])
            @account.transaction do
                transfer_transaction
            end
        end
    end

    # atm withdrawal
    def atmwithdraw
        @atm = @account.atm
    end

    def atmwithdraw_amount
        @atm = @account.atm
        if params[:cvv].to_i != @atm.cvv
            message_and_redirect(:alert,"Incorrect CVV")

        elsif params[:expiry_date] != @atm.expiry_date.strftime("%m/%Y").to_s
            message_and_redirect(:alert,"Incorrect Expiry date")

        elsif params[:amount].to_i  > 20000
            message_and_redirect(:alert,"You can only withdraw money less then 20000")

        else
            @account.transaction do
                atm_transaction
            end
        end
    end


    private

    def set_up_accounts_variable 
        @accounts = current_user.accounts
    end

    def set_up_account_variable
        @account = Account.find(params[:id])
    end

    def set_up_user_variable
        @user = current_user
    end

    def set_up_new_account_variable
        @account = Account.new
    end

    def respond_partial(name)
        respond_to do |format|
            format.js { render partial: "layouts/#{name}" }
        end
    end

    def message_and_redirect(key,value)
        flash[key] = value
        redirect_to accounts_path
    end

    def direct_transaction 
        @account.balance = @account.balance + params[:amount].to_f
        if @account.save
            Transaction.create(type_of_transaction: "Direct", medium: "Deposit",account_id: @account.id,amount: (params[:amount]).to_f, where: (@account.number).to_s,balance: @account.balance)
            message_and_redirect(:notice,"You have successfully deposited your money") 
        else
            message_and_redirect(:alert,"#{@account.errors.each{|error| p error}}")
        end
    end

    def loan_deposit
        @account.balance = @account.balance - params[:amount].to_f
        if @account.save
            Transaction.create(type_of_transaction: "Direct", medium: "Deposit",account_id: @account.id,amount: (params[:amount]).to_f, where: (@account.number).to_s, balance: @account.balance)
            message_and_redirect(:notice,"You have successfully deposited your loan installment")
        else 
            message_and_redirect(:alert,"#{@account.errors.each{|error| p error}}")
        end
    end
    
    def transfer_transaction
        @account.balance = @account.balance - params[:amount].to_f
        if @account.save
            Transaction.create(type_of_transaction: "Direct", medium: "Transfer",account_id: @account.id,amount: (params[:amount]).to_f, from: (@account.number).to_s, where: (params[:number]).to_s,balance: @account.balance)
            @account1 = Account.find_by(number: (params[:number]).to_i)
            @account1.balance = @account.balance + params[:amount].to_f
            @account1.save
            Transaction.create(type_of_transaction: "Direct", medium: "Credited",account_id: @account1.id,amount: (params[:amount]).to_f, from: (@account.number).to_s, where: (params[:number]).to_s,balance: @account.balance)
            message_and_redirect(:notice,"You have successfully Transfered your money")
        else 
            message_and_redirect(:alert,"#{@account.errors.each{|error| p error}}")
        end
    end

    def atm_transaction
        @account.balance = @account.balance - params[:amount].to_f
        if @account.save
            Transaction.create(type_of_transaction: "Indirect", medium: "Atm Withdrawal",account_id: @account.id,amount: (params[:amount]).to_f, from: (@account.number).to_s,balance: @account.balance)
            if @account.transactions.where(type_of_transaction: "Indirect").count > 5 && @account.type_of_account == "Saving"
                @account.balance = @account.balance - 500.00
                @account.save
                Transaction.create(type_of_transaction: "Direct",account_id: @account.id,amount: (500).to_f, from: (@account.number).to_s, remark: "penalty charged",balance: @account.balance)
            end
            message_and_redirect(:notice,"You have successfully withdraw your money")
        else
            message_and_redirect(:alert,"#{@account.errors.each{|error| p error}}")
        end
    end

    def withdrawal_transaction
        @account.balance = @account.balance - params[:amount].to_f
        if @account.save
        Transaction.create(type_of_transaction: "Direct", medium: "Withdrawal",account_id: @account.id,amount: (params[:amount]).to_f, from: (@account.number).to_s, balance: @account.balance)
        message_and_redirect(:notice,"You have successfully withdraw your money")
        else 
            message_and_redirect(:alert,"#{@account.errors.each{|error| p error}}")
        end   
    end

    
end

app/controllers/api/accounts_controller.rb
class   Api::AccountsController < Api::ApplicationController
    before_action :authenticate_user!
    
    protect_from_forgery with: :null_session

    def create 
        @user = current_user
        @account = Account.new(user_id: @user.id, type_of_account: params[:account][:type_of_account], branch_id: (params[:account][:branch_id]).to_i,balance: (params[:account][:balance]).to_f, number: rand(1000000000 .. 9999999999))
        if @account.save
            render json: {
                "notice": "Account has been created successfully."
            }
        else
            render json: {
                "alert": "error ocuured"
            }
        end
    end

    def balance
        @accounts = current_user.accounts
        render json: {
            "Accounts": @accounts
        }
    end

    def withdraw
        @account = Account.find_by(params[:number])
        @account.transaction do
            @account.balance = @account.balance - params[:amount].to_f
            if @account.save
                Transaction.create(type_of_transaction: "Direct", medium: "Withdrawal",account_id: @account.id,amount: (params[:amount]).to_f, from: (@account.number).to_s, balance: @account.balance)
                message_and_render("notice","You have successfully withdraw your money")
            else 
                message_and_render("alert", "error ocuured")
            end
        end
    end

    def atmwithdraw
        @account = Atm.find_by(number: params[:number].to_i).account
        @atm = Atm.find_by(number: params[:number].to_i)
        if @account == nil
            message_and_render("alert","Atm number is wrong")

        elsif params[:cvv].to_i != @atm.cvv
            message_and_render("alert","Incorrect CVV")

        elsif params[:expiry_date] != @atm.expiry_date.strftime("%m/%Y").to_s
            message_and_render("alert","Incorrect Expiry date")

        elsif params[:amount].to_i  > 20000
            message_and_render("alert","You can only withdraw money less then 20000")

        else
            @account.transaction do
                
                @account.balance = @account.balance - params[:amount].to_f
                if @account.save
                    Transaction.create(type_of_transaction: "Indirect", medium: "Atm Withdrawal",account_id: @account.id,amount: (params[:amount]).to_f, from: (@account.number).to_s,balance: @account.balance)
                    if @account.transactions.where(type_of_transaction: "Indirect").count > 5 && @account.type_of_account == "Saving"
                        @account.balance = @account.balance - 500.00
                        @account.save
                        Transaction.create(type_of_transaction: "Direct",account_id: @account.id,amount: (500).to_f, from: (@account.number).to_s, remark: "penalty charged",balance: @account.balance)
                    end
                    message_and_render("notice","You have successfully withdraw your money")
                else 
                    message_and_render("alert", "error ocuured") 
                end
            end
        end
    end

    def transfer
        unless Account.find_by(number: (params[:to]).to_i)
            message_and_render("alert","Incorrect Account number")
        else
            @account = Account.find_by(params[:from])
            @account.transaction do
                
                @account.balance = @account.balance - params[:amount].to_f
                if @account.save
                    Transaction.create(type_of_transaction: "Direct", medium: "Transfer",account_id: @account.id,amount: (params[:amount]).to_f, from: (@account.number).to_s, where: (params[:to]).to_s,balance: @account.balance)
                    @account1 = Account.find_by(number: (params[:to]).to_i)
                    @account1.balance = @account.balance + params[:amount].to_f
                    @account1.save
                    Transaction.create(type_of_transaction: "Direct", medium: "Credited",account_id: @account1.id,amount: (params[:amount]).to_f, from: (@account.number).to_s, where: (params[:to]).to_s,balance: @account.balance)
                    message_and_render("notice","You have successfully Transfered your money")
                else 
                    message_and_render("alert", "error ocuured")
                end
            end
        end
    end

    def message_and_render(key,value)
        render json: {
            "#{key}": "#{value}"
        }
    end
end

app/views/accounts/_open_account.html.erb
<%= form_for @account do |f| %>
  <div class="form-group">
    <%= f.label :type_of_account ,"Account Type"%>
    <%= f.select :type_of_account, [['Saving','Saving'],['Current','Current']], class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :branch_id ,"Select Branch you want to open account"%>
    <%= f.select :branch_id, options_for_select([["Select One", ""], ["1.Koramangala",'1'], ["2.Electronic", '2'], ["3.North",'3'], ["4.South",'4'], ["5.West",'5'], ["6.East",'6'], ["7.Dommalurru",'7']]), :class => 'genForm_dropBox' %>
    
  </div>
  <div class="form-group">
    <%= f.label :balance ,"Opening Balance"%>
    <%= f.number_field :balance,  class: 'form-control' %>
  </div>
  

  <%= f.submit "Submit" %>
<% end %>

app/views/accounts/_transfer-money.html.erb
<br>
<div class="container content-center">
    <%= form_with url: "transfer/#{@account.id}", method: :patch do |f| %>
        <div class="form-group">
            <%= f.label :number ,"Enter account number you want to transfer money:"%>
            <%= f.number_field :number %>
        </div>
        <div class="form-group">
            <%= f.label :amount ,"Enter amount money"%>
            <%= f.number_field :amount %>
        </div>
        
    
        
        <%= f.submit "Transfer Money", class:"btn btn-outline-success my-2 my-sm-0", data: { confirm: "Press okay to confirm" } %>
    <% end %>
    
    <br>
   <%= link_to ("Back"), accounts_path, class:"btn btn-outline-success my-2 my-sm-0"%> 
</div>

app/views/accounts/_withdraw-money.html.erb
<br>
<div class="container content-center">
    <%= form_with url: "withdraw/#{@account.id}", method: :patch do |f| %>
        <div class="form-group">
            <%= f.label :amount ,"Enter amount money"%>
            <%= f.number_field :amount %>
        </div>
        
    

        <%= f.submit "Withdraw", class:"btn btn-outline-success my-2 my-sm-0" %>
    <% end %>
    
    <br>
    <%= link_to "atmwithdraw/#{@account.id}", class:"btn btn-outline-success my-2 my-sm-0" do %>
        <%= "ATM Withdrawal"%>
    <%end%> 
   <%= link_to ("Back"), accounts_path, class:"btn btn-outline-success my-2 my-sm-0"%> 
</div>

app/views/accounts/atmwithdraw.html.erb
<br>
<div class="container content-center">
    <div class="row justify-content-center">
        <h1>ATM Withdrawal</h1>
    </div>
    <br>
    <%= form_with url: "/atmwithdraw/#{@account.id}", method: :patch do |f| %>    
        <div class="form-group">
            <%="Your atm number is: #{@atm.number}"%>
        </div>
        <div class="form-group">
            <%= f.label :cvv ,"CVV"%>
            <%= f.number_field :cvv%>
        </div>
        <div class="form-group">
            <%= f.label :expiry_date ,"Expiry date"%>
            <%= f.text_field :expiry_date , placeholder: "MM/YYYY"%>
        </div>
        <div class="form-group">
            <%= f.label :amount ,"Enter amount money"%>
            <%= f.number_field :amount %>
        </div>

        <%= f.submit "Withdraw", class:"btn btn-outline-success my-2 my-sm-0" %>
    <% end %>
    
</div>

app/views/accounts/balance.html.erb
<br>
<div class="container content-center">
    <div class="row justify-content-center">
        <h1>Account Balance details</h1>
    </div>
    <br>
        <div class="row justify-content-center">
            <div class="col-4">
                <strong><%= "Account Number " %></strong>
            </div>
            <div class="col-4">
            <strong><%= "Account Type " %> </strong>
                
            </div>
            <div class="col-4">
            <strong><%= "Balance"%></strong>
                 
            </div>
        </div>
    <% @accounts.each do |account|%>
        <div class="row justify-content-center">
            <div class="col-4">
                <%= "#{account.number}" %> 
            </div>
            <div class="col-4">
                <%= "#{account.type_of_account}" %> 
            </div>
            <div class="col-4">
                <%= "#{account.balance}"%> 
            </div>
        </div>
    <% end %>
    <br><br>
    <%= link_to ("Back"), accounts_path, class:"btn btn-outline-success my-2 my-sm-0"%> 
</div>

app/views/accounts/deposit.html.erb
<br>
<div class="container content-center">
    <div class="row justify-content-center">
        <h1>Deposit here</h1>
    </div>
    <br>
    <%= form_with  do |form| %>    
        <div class="dropdown  btn-secondary ">
            <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                Select account you want to Deposit
            </a>
            <div class="dropdown-menu">
                <% @accounts.each do |account|%>
                    <%= link_to (account.number), "/deposit/#{account.id}", class:"dropdown-item custom-1", :remote => true  %>
                <% end %>
            </div>
        </div>

    <% end %>
    <div class="deposit-money"></div>  
</div>

app/views/accounts/details.html.erb
<h1>User Details</h1>
<%= form_with do |f| %>
    <div class="form-group">
        
        <%= "First Name: #{@user.first_name.capitalize}" %>
    </div>

    <div class="form-group">
        
        <%= "Last Name: #{@user.last_name.capitalize}" %>
    </div>

    <div class="form-group">
        <%=  "City: #{@user.city.capitalize}" %>
    </div>

    <div class="form-group">
    
        <%= "Date of Birth: #{@user.dob.to_date}" %>
    </div>

    <div class="form-group">
        
        <%= "Email: #{@user.email}" %>
    </div>

    <div class="form-group">
        <strong><%= "Accounts:" %></strong>
    </div>
    <% @user.accounts.each do |account|%>
        <div class="form-group">
        <div class="row">
            <div class="col">
                <%= "Account Number: #{account.number} "%> 
            </div>
            <div class="col">
                <%= "Balance: #{account.balance}" %> 
            </div>
            <div class="col">
                <%= "Type: #{account.type_of_account}"%>
            </div>
        </div>
        </div>
    <% end%>
    
    <div class="form-group">
        
        <% if current_user.admin? %>
            <%= link_to ("Back"), dashboard_index_path, class:"btn btn-outline-success my-2 my-sm-0"%>
        <% else %>
            <%= link_to ("Back"), accounts_path, class:"btn btn-outline-success my-2 my-sm-0"%> 
        <% end %> 

    </div>
<% end %>

app/views/accounts/index.html.erb
<br>
<div class="container content-center">
  <div class="row justify-content-center">
    <h1>Welcome to user board</h1>
  </div>
  <br>
  <div class="row justify-content-center">
    <div class="col-4">
      <%= link_to ("Account Open"), new_account_path,  class:"btn btn-outline-success my-2 my-sm-0"%> 
    </div>
    <div class="col-4">
      <%= link_to ("Details"), users_path,  class:"btn btn-outline-success my-2 my-sm-0"%> 
    </div>
    <div class="col-4">
      <%= link_to ("View Balance"), balance_accounts_path,  class:"btn btn-outline-success my-2 my-sm-0"%> 
    </div>
  </div>
  <br>
  <div class="row justify-content-center">
    <div class="col-4">
      <%= link_to ("Transaction History"), transactions_path,  class:"btn btn-outline-success"%> 
    </div>
    <div class="col-4">
      <%= link_to ("Deposit"), deposit_path,  class:"btn btn-outline-success"%> 
    </div>
    <div class="col-4">
      <%= link_to ("Withdrawal"), withdraw_path,  class:"btn btn-outline-success"%> 
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-4">
      <%= link_to ("Transfer"), transfer_path,  class:"btn btn-outline-success"%> 
    </div>
    <div class="col-4">
      <%= link_to ("Apply for loan"), new_loan_path,  class:"btn btn-outline-success"%> 
    </div>
  </div>
</div>

app/views/accounts/new.html.erb
<%= render 'layouts/confirmform' %>
<div class="open-account"></div>
  

app/views/accounts/transactions.html.erb
<br>
<div class="container content-center">
    <div class="row justify-content-center">
        <h1>Accounts Transaction  history</h1>
    </div>
    <br>
    <%= form_with  do |form| %>
        <div class="dropdown  btn-secondary ">
            <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                Select account that you want to see transaction history
            </a>
            <div class="dropdown-menu">
                <% @accounts.each do |account|%>
                    <%= link_to (account.number), "/transaction/#{account.id}", class:"dropdown-item custom-1", :remote => true  %>
                <% end %>
            </div>
        </div>

    <% end %>
    <div class="transaction-history"></div>  
</div>

app/views/accounts/transfer.html.erb
<br>
<div class="container content-center">
    <div class="row justify-content-center">
        <h1>Transfer Money</h1>
    </div>
    <br>
    <%= form_with  do |form| %>    
        <div class="dropdown  btn-secondary ">
            <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                Select account from you want to Transfer
            </a>
            <div class="dropdown-menu">
                <% @accounts.each do |account|%>
                    <% if account.type_of_account != "Loan"%>
                        <%= link_to (account.number), "/transfer/#{account.id}", class:"dropdown-item custom-1", :remote => true  %>
                    <% end %>
                <% end %>
            </div>
        </div>

    <% end %>
    <div class="transfer-money"></div>  
</div>

app/views/accounts/withdraw.html.erb
<br>
<div class="container content-center">
    <div class="row justify-content-center">
        <h1>Withdraw here</h1>
    </div>
    <br>
    <%= form_with  do |form| %>    
        <div class="dropdown  btn-secondary ">
            <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                Select account you want to withdraw
            </a>
            <div class="dropdown-menu">
                <% @accounts.each do |account|%>
                    <% if account.type_of_account != "Loan"%>
                        <%= link_to (account.number), "/withdraw/#{account.id}", class:"dropdown-item custom-1", :remote => true  %>
                    <% end %>
                <% end %>
            </div>
        </div>

    <% end %>
    <div class="withdraw-money"></div>  
</div>